theme: jekyll-theme-minimal
title: "~{ VAIBHAV JAIN }~"
logo: /assets/img/logo.jpg
description: Self-starter | Full-stack developer | 24/7 remote
repository: vaibhav-jain/vaibhav-jain.github.io
plugins:
  - jemoji
